apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagu
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: todo
  source:
    path: deploy/argocd/manifests/applications/dagu
    repoURL: git@github.com:scottseotech/todo-platform.git
    targetRevision: main 
