apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-mcp-swagger
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/argocd/manifests/applications/todo-mcp-swagger
    repoURL: git@github.com:scottseotech/todo-platform.git
    targetRevision: main 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true