apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-bot
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: todo
    server: https://kubernetes.default.svc
  project: todo
  source:
    path: deploy/argocd/manifests/applications/todo-bot
    repoURL: git@github.com:scottseotech/todo-platform.git
    targetRevision: main 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true