apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app.kubernetes.io/name: docs
  name: docs
  namespace: todo
spec:
  ingressClassName: traefik
  rules:
  - host: docs.scottseo.tech
    http:
      paths:
      - backend:
          service:
            name: docs
            port:
              number: 80
        path: /
        pathType: Prefix