resources:
- ingress.yaml
- statefulset.yaml
- service.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: dagu
  newName: curiosinauts/scottseotech-dagu
  newTag: 21f067c
