apiVersion: v1
kind: Service
metadata:
  name: todo-mcp-swagger
  namespace: todo
spec:
  type: ClusterIP
  selector:
    app: todo-mcp-swagger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 