apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app.kubernetes.io/name: todo-bot
  name: todo-bot
  namespace: todo
spec:
  ingressClassName: traefik
  rules:
  - host: todo-bot.scottseo.tech
    http:
      paths:
      - backend:
          service:
            name: todo-bot
            port:
              number: 8082
        path: /
        pathType: Prefix