apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-bot
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
        - name: todo-bot
          image: todo-bot
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: TODO_API_URL
              value: http://todo-api.default.svc.cluster.local
            - name: TODO_MCP_URL
              value: http://todo-mcp.default.svc.cluster.local
            - name: FLASK_ENV
              value: development
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: todo-bot-secret
                  key: SLACK_BOT_TOKEN
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: todo-bot-secret
                  key: SLACK_APP_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: todo-bot-secret
                  key: OPENAI_API_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10 
          ports:
            - containerPort: 8082
          resources:
            limits:
              memory: "1024Mi"

