resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# This adds the suffix to metadata.name
# nameSuffix: -todo-mcp-swagger

# # Use patch files to prevent kustomize edit set from mangling inline yaml into string
# patches:
# - path: ingress.yaml

# Beaware this will update selector values as well. 
# https://patrick-picard.medium.com/kustomization-applying-labels-gotchas-a53f87277661
labels:
- includeSelectors: true
  pairs:
    app: todo-mcp-swagger

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: todo-mcp-swagger
  newName: curiosinauts/scottseotech-todo-mcp-swagger
  newTag: 6b5fff7
