apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
    app.kubernetes.io/name: dagu 
  name: dagu
  namespace: todo
spec:
  ingressClassName: traefik
  rules:
  - host: dagu.scottseo.tech
    http:
      paths:
      - backend:
          service:
            name: dagu
            port:
              number: 8080 
        path: /
        pathType: Prefix