apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-mcp
  labels:
    app: todo-mcp
    release: kube-prometheus-stack
  namespace: todo
spec:
  selector:
    matchLabels:
      app: todo-mcp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
