apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-db
spec:
  instances: 2
  
  storage:
    size: 25Gi

  walStorage:
    size: 25Gi
  
  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: todo_db
      owner: todo_db_admin
      secret:
        name: todo-db-admin-secret
      options:
        - "--set=search_path=todo_db"

  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/"
      endpointURL: "https://rustfs.codingworks.me"
      s3Credentials:
        accessKeyId:
          name: rustfs-secret
          key: RUSTFS_ACCESS_KEY
        secretAccessKey:
          name: rustfs-secret
          key: RUSTFS_SECRET_KEY
        region:
          name: rustfs-secret
          key: RUSTFS_REGION
      wal:
        compression: bzip2
      data:
        compression: gzip

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

---

apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: todo-db-scheduled-backup
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: todo-db